language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t prashantjdrew/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prashantjdrew/react-test npm test

after_success:
  - docker build -t prashantjdrew/multi-client ./client
  - docker build -t prashantjdrew/multi-nginx ./nginx
  - docker build -t prashantjdrew/multi-server ./server
  - docker build -t prashantjdrew/multi-worker ./worker
  # Log into docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push prashantjdrew/multi-client
  - docker push prashantjdrew/multi-nginx
  - docker push prashantjdrew/multi-server
  - docker push prashantjdrew/multi-worker
